#!/bin/sh

figlet "                Alain"
echo "              version 1.2.0" "made by theAnvil01"
echo "       You can connect me in telegram : @theAnvil01"
 echo "                Efficient Sub-Domain Finder" 
 echo "" 
	read -p "Enter password:" pass
	md5=$(echo "$pass" | md5sum)
	case $md5 in
			"526b323e49632357e4ea4d5bf750cfea  -") echo "Authentication Sucessfull"
	
	  read -p "Enter your domain: " dom 
          echo "" 
          echo "Want to ping Domain for checking , host is up or Not" 
          read -p "(yes/no)"  ping 
          
          case $ping in 
               
                yes) 
                       echo " starting ping $dom" 
                       ping -c 4 $dom ;;
                       
                no)    echo "You selected No";;
                 
                 *) echo "invalid Options, try Again" ''
                 
                 esac        
echo ""
echo ""

echo  "Available options: \n1. Want to use sublist3r only \n2. Want to use amass and sublist3r (slow but Efficient) \n3. want to Use Crt.sh(Quick) \n4. Want to use all Three \n5. Amass only"
echo "" 
read -p "Choose options from above:" op 

  
  case $op in
              1)       mkdir "$dom"
			cd "$dom"
                       echo "please wait and have some coffee"
                       echo "starting up sublist3r..." && echo "sublist3r started" && sublist3r -d $dom -o sublist3r.$dom.txt >>/dev/null
                       echo ""
                       
               
                       echo "sublist3r finished his task"
                       	
                    
                 echo ""  ;;

              2)
              mkdir "$dom"
                cd "$dom"
                echo "please wait and have some coffee"
                echo ""
                 echo " Starting up amass" && echo "amass  started" && amass enum  -d $dom -o amass.$dom.txt >> /dev/null
                echo ""
              
                
	        echo ""
                echo "amass finished his task"
                echo "" 
                echo "starting up sublister..." && echo "sublist3r started"  && sublist3r -d $dom -o sublis3r.$dom.txt >>/dev/null 
                echo ""
                echo "sublister finished his task"
                echo ""
                

               
                echo " finishing up things"
                
         
                echo "exiting" ;;
               
               3)
                   mkdir "$dom"
		cd "$dom"
                  curl -s https://crt.sh/\?q\=%25.$dom\&output\=json | jq -r ' .[].name_value' | sed 's/\*\.//g' | tee $dom.txt >>/dev/null
                   ;;

               4)
                  mkdir "$dom"
                  cd "$dom"   
                    echo "please wait and have some coffee"
                   
                    echo " starting up sublist3r..." && echo "   sublist3r started" && sublist3r -d $dom -o sublis3r.$dom.txt >>/dev/null
                    echo ""
                    echo " sublist3r finished his task"
                    echo ""
                    
                  
                 echo "Starting up amass" && echo "    amass  started" && amass enum  -d $dom -o amass.$dom.txt >> /dev/null
                echo ""
	        echo ""
                echo "amass finished his task"
                echo ""
                
            
             curl -s https://crt.sh/\?q\=%25.$dom\&output\=json | jq -r ' .[].name_value' | sed 's/\*\.//g' | tee crt.$dom.txt >> /dev/null ;;
             
               
               5)mkdir "$dom"
                  cd "$dom"	
                echo "" 
                echo " Starting up amass" && echo "amass  started" && amass enum  -d $dom -o amass.$dom.txt >> /dev/null
                  echo "done";;
                       
                *) 
                    echo  " wrong input Try Again";;
               esac              
   
  echo  " options For subdomain: \n1. keep raw \n2. compile and  sort unique domain"
  echo ""
  echo ""
  read -p "choose options from above(2 recommended)" sort
   
   case $sort in 
   
      1) echo " keeping it Raw"
         echo ""
     
         echo "" 
         echo "Bye,keep hunting bugs"
         echo ""
         echo ""
         echo "";;
       
       2)  echo "sorting unique domains" &&  cat *.txt | sort -u >> "$dom(unique).txt" 

          echo ""
          echo ""
        

          echo "Done"
          echo ""
          echo ""
        echo "Total unique sub-domain:"; cat "$dom(unique).txt" | wc -l 
       echo ""
       echo ""
       echo "want to resolve urls "
        echo  "Want to get resolved urls with status code. \n1. Yes  \n2. No"
 echo "" 
 read -p "(Choose 1/2)" mn
 
   case $mn in 
             
              1) echo " resolving subdomains"
               echo "we use httpx for this method " 
                    cat "$dom(unique).txt" | httpx -status-code | tee httpx >> /dev/null
                    echo "all finished "
                    echo "Cleaning the mess"
                           rm *.txt
                           mv httpx urls.txt
                            echo "Total acquired subdomains:" 
                        cat urls.txt | wc -l 
                     echo ""
                     echo "status 200 code urls:"
                     cat urls.txt | grep 200 | wc -l 
                     echo "exiting" ;;
                                      
                            
                               
                                          
                                             
                                             
                                             2) echo "You have choosed NO";;
                                             
                                             *) echo "invalid options";;
                                             
                                             esac;;
                                             
        
     				   *) echo "invalid option,Try Again";;  
        
 					esac;;
 					
 
	*) echo "incorrect password,try again";;
	esac
	
                                             
                                             
                               
                                               
                                             
                                                              

                                              
                                             
                                              
                                              
                                                                
                                   
       
        
         
                   
              
